---
version: "2.1"

networks:
  web:
    external: true
    
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/appdata:/config
      - /path/to/data:/data
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.frontend.rule=Host:next.cemtech.eu
      - traefik.port=443
